'use client';
import { Box, Typography } from '@mui/material';
import { zikkitColors as c } from '@/styles/theme';

const S = ({ t, children }: { t: string; children: React.ReactNode }) => (
  <Box sx={{ mb: 4 }}>
    <Typography sx={{ fontSize: 16, fontWeight: 700, color: c.text, mb: 1 }}>{t}</Typography>
    <Typography sx={{ fontSize: 13, color: c.text2, lineHeight: 1.9 }}>{children}</Typography>
  </Box>
);

export default function TermsPage() {
  return (
    <Box sx={{ bgcolor: c.bg, minHeight: '100vh', color: c.text, py: 6, px: { xs: 2, md: 4 }, maxWidth: 800, mx: 'auto' }}>
      <Typography sx={{ fontSize: 28, fontWeight: 900, fontFamily: 'Syne, sans-serif', mb: 1 }}>Terms of Service</Typography>
      <Typography sx={{ fontSize: 13, color: c.text3, mb: 4 }}>Last updated: March 2026</Typography>

      <S t="1. Agreement to Terms">
        By accessing or using the Zikkit platform, you agree to be bound by these Terms of Service. If you do not agree, you may not use the platform. These terms constitute a legally binding agreement between you and Zikkit Ltd.
      </S>
      <S t="2. Description of Service">
        Zikkit provides a cloud-based field service management platform including AI-powered voice answering, job management, CRM, quoting, invoicing, technician management, payroll calculations, GPS tracking, SMS automation, and client portal features. The platform is designed for field service businesses including but not limited to HVAC, plumbing, electrical, garage door, locksmith, and chimney services.
      </S>
      <S t="3. Account Registration">
        You must provide accurate and complete information when creating an account. You are responsible for maintaining the confidentiality of your account credentials. You must be at least 18 years old to use the platform. Each business account is owned by the registered business owner.
      </S>
      <S t="4. Subscription and Payment">
        Zikkit offers subscription plans billed monthly or annually. Prices are listed on our pricing page and may change with 30 days notice. A free trial period of 30 days is provided for new accounts. After the trial period, a valid payment method is required to continue using the service. Failed payments may result in service suspension after a 7-day grace period. All fees are non-refundable except as required by law.
      </S>
      <S t="5. AI Voice Bot">
        The AI voice bot is provided as an automated answering service. While designed to be accurate and helpful, the bot may occasionally provide incorrect or incomplete information. Zikkit is not liable for any actions taken based on information provided by the AI bot. You are responsible for reviewing leads and information generated by the bot. The bot does not replace professional advice or emergency services.
      </S>
      <S t="6. Data Ownership and Privacy">
        You retain full ownership of all business data you enter into the platform. Zikkit stores your data securely using industry-standard encryption. We do not sell your data to third parties. Upon account termination, you may request an export of your data within 30 days. After 30 days, data may be permanently deleted. See our Privacy Policy for full details.
      </S>
      <S t="7. Acceptable Use">
        You agree not to use the platform for any unlawful purpose, attempt to gain unauthorized access to any part of the service, interfere with or disrupt the service, use the platform to send spam or unsolicited messages, or misrepresent your identity or affiliation.
      </S>
      <S t="8. Service Availability">
        We strive for 99.9% uptime but do not guarantee uninterrupted service. Scheduled maintenance will be communicated in advance when possible. We are not liable for service interruptions caused by factors outside our control including internet outages, natural disasters, or third-party service failures.
      </S>
      <S t="9. Limitation of Liability">
        To the maximum extent permitted by law, Zikkit shall not be liable for any indirect, incidental, special, consequential, or punitive damages. Our total liability shall not exceed the amount paid by you in the 12 months preceding the claim. This limitation applies regardless of the theory of liability.
      </S>
      <S t="10. Termination">
        Either party may terminate the subscription at any time. Upon termination by you, access continues until the end of the current billing period. We may terminate your account immediately if you violate these terms. Upon termination, your right to use the platform ceases. Data export is available for 30 days after termination.
      </S>
      <S t="11. Changes to Terms">
        We may update these terms from time to time. Material changes will be communicated via email or in-app notification at least 30 days before they take effect. Continued use of the platform after changes constitutes acceptance.
      </S>
      <S t="12. Governing Law">
        These terms are governed by the laws of the State of Delaware, United States. Any disputes shall be resolved through binding arbitration in accordance with the rules of the American Arbitration Association.
      </S>
      <S t="13. Contact">
        For questions about these terms, contact us at legal@zikkit.com.
      </S>
    </Box>
  );
}
