"use client";
import { createTheme, type ThemeOptions } from "@mui/material/styles";

const palette = {
  bg: "#F5F0EB",
  surface1: "#FAF7F4",
  surface2: "#F5F0EB",
  surface3: "#EFEBE7",
  surface4: "#E7E2DD",
  surface5: "#DDD8D3",
  glass: "rgba(0,0,0,0.02)",
  glass2: "rgba(0,0,0,0.04)",
  glass3: "rgba(0,0,0,0.07)",
  glassBorder: "rgba(0,0,0,0.06)",
  border: "rgba(0,0,0,0.06)",
  border2: "rgba(0,0,0,0.10)",
  border3: "rgba(0,0,0,0.16)",
  accent: "#4F46E5",
  accent2: "#6366F1",
  accent3: "#3730A3",
  accentGlow: "rgba(79,70,229,0.12)",
  accentDim: "rgba(79,70,229,0.08)",
  accentMid: "rgba(79,70,229,0.14)",
  amber: "#D97706",
  amberDim: "rgba(217,119,6,0.10)",
  blue: "#2563EB",
  blueDim: "rgba(37,99,235,0.08)",
  purple: "#7C3AED",
  purpleDim: "rgba(124,58,237,0.08)",
  violet: "#7C3AED",
  violetDim: "rgba(124,58,237,0.08)",
  hot: "#E11D48",
  hotDim: "rgba(225,29,72,0.08)",
  warm: "#D97706",
  warmDim: "rgba(217,119,6,0.08)",
  green: "#059669",
  greenDim: "rgba(5,150,105,0.08)",
  teal: "#0D9488",
  tealDim: "rgba(13,148,136,0.08)",
  text: "#1C1917",
  text2: "#57534E",
  text3: "#A8A29E",
  text4: "#D6D3D1",
};

const t: ThemeOptions = {
  palette: {
    mode: "light",
    primary: { main: palette.accent, light: palette.accent2, dark: palette.accent3, contrastText: "#fff" },
    secondary: { main: palette.violet, contrastText: "#fff" },
    error: { main: palette.hot },
    warning: { main: palette.warm },
    success: { main: palette.green },
    info: { main: palette.teal },
    background: { default: palette.bg, paper: palette.surface1 },
    text: { primary: palette.text, secondary: palette.text2, disabled: palette.text3 },
    divider: palette.border,
  },
  typography: {
    fontFamily: "'Rubik', 'Heebo', system-ui, sans-serif",
    h1: { fontWeight: 700, fontSize: "1.75rem", color: palette.text },
    h2: { fontWeight: 700, fontSize: "1.35rem", color: palette.text },
    h3: { fontWeight: 600, fontSize: "1.15rem", color: palette.text },
    h4: { fontWeight: 600, fontSize: "1rem" },
    h5: { fontWeight: 600, fontSize: "0.9rem" },
    h6: { fontWeight: 600, fontSize: "0.82rem" },
    body1: { fontSize: "0.875rem", lineHeight: 1.6 },
    body2: { fontSize: "0.8125rem", lineHeight: 1.6 },
    caption: { fontSize: "0.6875rem", fontWeight: 500 },
    button: { fontWeight: 600, textTransform: "none" as const, fontSize: "0.8125rem" },
  },
  shape: { borderRadius: 10 },
  components: {
    MuiCssBaseline: { styleOverrides: {
      body: { background: palette.bg, color: palette.text, WebkitFontSmoothing: "antialiased" },
      "::-webkit-scrollbar": { width: "5px", height: "5px" },
      "::-webkit-scrollbar-track": { background: "transparent" },
      "::-webkit-scrollbar-thumb": { background: "rgba(0,0,0,0.1)", borderRadius: "99px" },
      "::-webkit-scrollbar-thumb:hover": { background: "rgba(0,0,0,0.18)" },
      "@keyframes fadeUp": { from: { opacity: 0, transform: "translateY(12px)" }, to: { opacity: 1, transform: "translateY(0)" } },
      ".zk-fade-up": { animation: "fadeUp 0.3s ease" },
      ".zk-fade-up-1": { animation: "fadeUp 0.3s ease 0.05s forwards", opacity: 0 },
      ".zk-fade-up-2": { animation: "fadeUp 0.3s ease 0.1s forwards", opacity: 0 },
      ".zk-fade-up-3": { animation: "fadeUp 0.3s ease 0.15s forwards", opacity: 0 },
      ".zk-fade-up-4": { animation: "fadeUp 0.3s ease 0.2s forwards", opacity: 0 },
    }},
    MuiButton: { styleOverrides: {
      root: { borderRadius: 20, padding: "8px 20px", fontWeight: 600, fontSize: "0.8125rem", boxShadow: "none", "&:hover": { boxShadow: "none" } },
      containedPrimary: { background: palette.accent, color: "#fff", "&:hover": { background: palette.accent3, boxShadow: "0 2px 8px rgba(79,70,229,0.2)" } },
      outlined: { borderColor: palette.border2, color: palette.text2, background: palette.surface3, "&:hover": { borderColor: palette.accent, color: palette.accent, background: palette.accentDim } },
    }, defaultProps: { disableElevation: true } },
    MuiTextField: { styleOverrides: { root: {
      "& .MuiOutlinedInput-root": {
        background: palette.surface1, borderRadius: 10, fontSize: "0.875rem",
        "& fieldset": { borderColor: palette.border2 },
        "&:hover fieldset": { borderColor: palette.border3 },
        "&.Mui-focused fieldset": { borderColor: palette.accent, boxShadow: "0 0 0 3px " + palette.accentDim },
      },
      "& .MuiInputBase-input": { padding: "10px 14px", color: palette.text },
    }}},
    MuiSelect: { styleOverrides: { root: { background: palette.surface1, borderRadius: 10, fontSize: "0.875rem" } } },
    MuiCard: { styleOverrides: { root: {
      background: palette.surface1, border: "none", borderRadius: 12,
      boxShadow: "0 1px 4px rgba(0,0,0,0.04)", transition: "all 0.2s ease",
      "&:hover": { boxShadow: "0 4px 16px rgba(0,0,0,0.07)" },
    }}},
    MuiDialog: { styleOverrides: { paper: {
      background: palette.surface1, border: "none", borderRadius: 16,
      boxShadow: "0 24px 60px rgba(0,0,0,0.12)",
    }}},
    MuiChip: { styleOverrides: { root: { borderRadius: 20, fontWeight: 600, fontSize: "0.6875rem" } } },
    MuiTableHead: { styleOverrides: { root: { "& th": {
      fontSize: "0.6875rem", fontWeight: 500, color: palette.text3,
      borderBottom: "1px solid " + palette.border, background: "transparent", padding: "8px 14px",
    }}}},
    MuiTableBody: { styleOverrides: { root: {
      "& td": { padding: "11px 14px", borderBottom: "1px solid rgba(0,0,0,0.04)", fontSize: "0.8125rem", color: palette.text },
      "& tr:last-child td": { borderBottom: "none" },
      "& tr:hover td": { background: palette.surface3 },
    }}},
    MuiTooltip: { styleOverrides: { tooltip: { background: palette.text, color: "#fff", fontSize: "0.75rem", fontWeight: 500, borderRadius: 8 } } },
    MuiDrawer: { styleOverrides: { paper: { background: palette.surface1 } } },
    MuiPaper: { styleOverrides: { root: { backgroundImage: "none" } } },
    MuiTabs: { styleOverrides: { indicator: { background: palette.accent, height: 2, borderRadius: 2 } } },
  },
};

export const theme = createTheme(t);
export { palette as zikkitColors };
